
startAdr            = $3500
tileMapLAdr         = $3800
tileMapRAdr         = $3C00
picLAdr             = $4000
picRAdr             = $6000
scrollMemAdr		= $8000
dlAdr               = $8030
pmLAdr              = $8000+$0300
pmRAdr              = $8800+$0300



LEFT_BORDER = 48 ;horizontal sprite position equal to left border of screen
LEFT_BORDER_SH = 47 ;horizontal sprite position equal to left border of screen when line is shifted due to hsync delay


COLOR_BLACK = $00
COLOR_WHITE = $0E
COLOR_GREY1 = $0A
COLOR_GREY2 = $06 ;$08
COLOR_GREY3 = $04 ;$06 ;$04
COLOR_PINK = $3A
COLOR_YELLOW = $EC ;$EE
COLOR_LBROWN = $28 ;$16 ;$18 ;$26
COLOR_GREEN = $CA ;$C8 ;$BA
COLOR_BROWN = $F4 ;$14 ;$F4 is more ore less equal on both PAL and NTSC
COLOR_PURPLE = $48 ;$4A
COLOR_BLUE = $64
COLOR_RED = $36
COLOR_LBLUE = $66 ;$68
