*         1544    030784
** * ** * ** * ** * ** * ** * ** * ** * **
**                                      **
**     Asteroids for the Atari 3600     **
**                                      **
** * ** * ** * ** * ** * ** * ** * ** * **

*
*
** RASTDEF.S **
** ASTEROIDS FOR THE ATARI 3600 **
** THIS FILE CONTAINS MEMORY STORAGE **
**  AND GENERAL EQUATES. **
**
** MODIFIED FOR MARIA 2 **
*
	icl	"maria.asm"
*
*
** HSC INTERFACE
HSCRAM    EQU     $1E00
HSCSETRS  EQU     $3FEB
HSCSTAT   EQU     $3FF7
HSCATRCT  EQU     $3FFA
HSCENTER  EQU     $3FFD

** IMMEDIATES
ICON      EQU     $07
SMALL     EQU     $10
MEDIUM    EQU     $21
LARGE     EQU     $32
SHIP      EQU     $23
SMALLUFO  EQU     $14
LARGEUFO  EQU     $25
SHOT      EQU     $06
OPENSHIP  EQU     $FF

XPOSMIN   EQU       0
XPOSMAX   EQU     159
YPOSMIN   EQU       0
YPOSMAX   EQU     191

NOVICED   EQU      60
TOUGHD    EQU      90
EXPERTD   EQU     110

MAXVEL    EQU     $20

MINDIFF   EQU     $00
MAXDIFF   EQU     $03
MINMODE   EQU     $FF
MAXMODE   EQU     $02

SELDLY    EQU     $10
RACKDLYC  EQU     $25

* EQUATES FOR DRIVER STATE MACHINE.
TITLEST   EQU     1
MENUST    EQU     2
AUTOST    EQU     3
HSCST     EQU     4
PLAYST    EQU     5
PAUZST    EQU     6

TITLEONT  EQU     0
TITLEOFT  EQU     TITLEONT+$02		;2 * 8.3 = 17 SECONDS

AUTOOFFT  EQU     $04

MENUOFFT  EQU     $07

* EQUATES FOR FINITE STATE MACHINE - FSM
DEAD      EQU     $FF
OK        EQU     0
BIRTH     EQU     1
HYPER     EQU     2
DEATH     EQU     3
COMPOVER  EQU     4

ENTERT    EQU     1
RESINT    EQU     ENTERT+$28
PMSGOFFT  EQU     RESINT+$28
PMSGT     EQU     PMSGOFFT+$28

HYPENDT   EQU     1
HYPERT    EQU     HYPENDT+$28

NEWGAMET  EQU     1
GOVERT    EQU     NEWGAMET+$60
POMSGOFT  EQU     GOVERT+$10
POMSGT    EQU     POMSGOFT+$30
SWITCHT   EQU     POMSGT+$5
DIET      EQU     SWITCHT+$10

* 6116 RAM WHICH IS >ON< ZERO PAGE:

/*

	ORG     $40
RANDPTR0:
	.ds		1
RANDPTR1:
	.ds		1

HISCORE:
	.ds		4		;HIGH SCORE

SCORE:
	.ds		4		;PLAYER ONE SCORE DEC. MODE
SCORE2:
	.ds		4		;PLAYER TWO SCORE DEC. MODE
COMBSCOR:
	.ds		4		;COMBINED SCORE DEC. MODE

MENLEFT:
	.ds		1		;PLAYER1 NUMBER OF MEN LEFT
MENLEFT2:
	.ds		1		;PLAYER2 NUMBER OF MEN LEFT
MENLEFTC:
	.ds		1		;POOL OF LIVES FOR TEAM PLAY

TEMP:
	.ds		16		;GAMEPLAY TEMP
TEMPI:
	.ds		5		;LOADER TEMP

FREE:
	.ds		12		;FREE POINTERS, NOT FREE SPACE


FRMCNT:
	.ds		1
LASTFRMC:
	.ds		1

NMICTRL:
	.ds		1		;VALUE OF CTRL FOR HSC SPECIAL NMIHNDL

PLAYER:
	.ds		1		;WHICH PLAYER
SCORER:
	.ds		1		;WHICH PLAYER IS CURRENTLY SCORING
GAMSTATE:
	.ds		1		;STATE FOR DRIVER.
DTIMER:
	.ds		2		;TIMER FOR DRIVER - TWO BYTES ACCURACY
STATE:
	.ds		2		;STATE FOR FSM, ONE FOR EACH PLAYER
TIMER:
	.ds		2		;TIMER FOR FSM, ONE FOR EACH PLAYER
MODE:
	.ds		1		;GAME MODE: FF = 1PL, 0=2PL, 1=TP, 2=CP
DIFF:
	.ds		1		;GAME DIFFICULTY LEVEL
MAXLVL:
	.ds		1		;MAXIMIUM LEVEL AT THIS DIFF SETTING
LVLINC:
	.ds		4		;INCREMENTS TO LEVEL
LEVEL:
	.ds		2
OFFPLAY2:
	.ds		1		;OFFSET FOR PLAYER2 DATA SET

STATUS:
	.ds		32		;OBJECT STATUS FOR PLAYER1 GAME
SH2STAT:
	.ds		1		;SHIP STATUS FOR 2 PLAYER GAME
MSGICONS:
	.ds		3		;STATUS FOR MESSAGE ICONS
PARTSTAT:
	.ds		8		;STATUS FOR SHIP'S PARTS FOR COLLISIONS

FIREBUT1:
	.ds		1		;SOFT REGISTERS
FIREBUT2:
	.ds		1
HYPBUT1:
	.ds		1
HYPBUT2:
	.ds		1
STARTBUT:
	.ds		1		;FIREBUT1 EXCEPT DURING AUTOST
SWCHAVAL:
	.ds		1
SWCHBVAL:
	.ds		1
SWCHBITS:
	.ds		1
ONEBUT:
	.ds		1		;PLAYER HAS 1 BUTTON JOYSTICK:
					; BIT 4 = P0, BIT 3 = P1

SHIPDIR:
	.ds		1		;PLAYER1 SHIP DIRECTION
SHIPDIR2:
	.ds		1		;PLAYER2 SHIP DIRECTION
RACKNUM:
	.ds		1		;PLAYER1 RACK NUMBER
RACKNUM2:
	.ds		1		;PLAYER2 RACK NUMBER
ROCKTOT:
	.ds		1		;PLAYER1 ROCK TOTAL
ROCKTOT2:
	.ds		1		;PLAYER2 ROCK TOTAL
STARTNUM:
	.ds		2		;STARTING NUMBER OF ROCKS FOR EACH

BCOUNTER:
	.ds		1		;BEAT COUNTER FOR BACKGROUND TUNE
BEATVAL:
	.ds		1		;BEAT VALUE FOR COUNTER, DECREASES
BEATRATE:
	.ds		1		;BEAT RATE, FOR CHANGE OF BEATVAL
WHICHBT:
	.ds		1		;BEAT NUMBER, TOGGLES BETWEEN 0 AND 1
TUNNUM:
	.ds		2		;NUMBER OF TUNE IN EACH CHANNEL
TINDEX:
	.ds		6		;INDEX INTO TUNE TABLE
TDURCNT:
	.ds		6		;TUNE DURATION COUNTERS
TTEMP     EQU     TEMPI		;THIS IS PROBABLY SAFE, SINCE TUNER
				; AND LOADER NEVER INTERRUPT EACH OTHER

FIRESTAT:
	.ds		2
SHOTCNT:
	.ds		6		;TIMER FOR ALL SHOTS
USHOTCNT:
	.ds		1		;COUNTDOWN TIMER FOR UFO SHOTS
RTIMER:
	.ds		1		;TIMER FOR UFO ENTRY
SDELAY:
	.ds		1		;PERCENTAGE OF LARGE
EDELAY:
	.ds		1		;COUNTDOWN TIL NEXT
UFOACC:
	.ds		1		;THRESHOLD OF UFO ACCURACY
SOFTCOLR:
	.ds		16		;SOFT COPY OF FIRST 4 PALETTES.

CLAMP:
	.ds		1		;CLAMP, USED BY DAMPING SYSTEM TO
					; STOP DRIFT
LOADFLAG:
	.ds		1		;FLAG CLEARED AT END OF LOADER.

SELCNT:
	.ds		1		;DEBOUNCER/COUNTER FOR MENU SELECT
RACKDLY:
	.ds		1		;TIMER FOR NEW RACK START
COMPFLAG:
	.ds		1		;FLAG FOR COMP PLAY TERMINATION
RUBFLAG:
	.ds		1		;RUBBER SHIP BOUNCE FLAG.
TURKEY:
	.ds		1
CHICKEN:
	.ds		1

*/


* 6116 RAM WHICH IS >NOT< ON ZERO PAGE:
	org     $1800
STATUS2:
	.ds		32		;OBJECT STATUS FOR TWOPLAYER GAME
**			;$20 LONG ARRAYS FOR STATE VARIABLES
**			;OF EACH OBJECT

XVELL:
	.ds		$20		;LOW BYTE X VELOCITY
XVELLP2:
	.ds		1		;SECOND PLAYER FOR TEAM PLAY

XVELH:
	.ds		$20		;HIGH BYTE X VELOCITY
XVELHP2:
	.ds		1

YVELL:
	.ds		$20		;LOW BYTE Y VELOCITY
YVELLP2:
	.ds		1

YVELH:
	.ds		$20		;HIGH BYTE Y VELOCITY
YVELHP2:
	.ds		1

XPOSH:
	.ds		$20		;HIGH BYTE X POSITION
XPOSHP2:
	.ds		1
	.ds		3

YPOSH:
	.ds		$20		;HIGH BYTE Y POSITION
YPOSHP2:
	.ds		1
	.ds		3

XPOSL:
	.ds		$20		;LOW BYTE X POSITION
XPOSLP2:
	.ds		1

YPOSL:
	.ds		$20		;LOW BYTE Y POSITION
YPOSLP2:
	.ds		1

ACYC:
	.ds		$20		;LOW BYTE STAMP ADDR
ACYCP2:
	.ds		1
	.ds		3
ANIMAT	EQU		ACYC+24
ACYC2:
	.ds		$20
COLXPOSH:
	.ds		$20
COLXP2:
	.ds		1
	.ds		3
PARTPOSX:
	.ds		8
COLYPOSH:
	.ds		$20
COLYP2:
	.ds		1
	.ds		3
PARTPOSY:
	.ds		8

XVELH2:
	.ds		$20
YVELH2:
	.ds		$20
XPOSH2:
	.ds		$20
YPOSH2:
	.ds		$20
XVELL2:
	.ds		$20
YVELL2:
	.ds		$20

TDURTAB:
	.ds		6		;TUNE DURATIONS

MINXVEL:
	.ds		1		;MINIMUM ROCK VELOCITIES
MINYVEL:
	.ds		1		; INCREASE AS DIFFICULTY
XVELLL:
	.ds		1		;LOW,LOW BYTE OF VELOCITY
XVELLL2:
	.ds		1		; USED BY DAMPING SYSTEM TO
YVELLL:
	.ds		1		; MAINTAIN SMOOTH, EXPONENTIAL
YVELLL2:
	.ds		1		; DECELLERATION AT LOW VELOCITIES.

BLANKDL:
	.ds		2		;DUMMY DISPLAY LIST: GETS ZEROED
DLL:
	.ds		$33		;DISPLAY LIST LIST: COPY OF DLLTAB
PALS:
	.ds		33		;SOFTWARE COPY OF PALETTE/WIDTH INFO
	.ds		3
PALS2:
	.ds		23		;TEMP COPY

FLASH:
	.ds		1		;KLUDGE FLAG FOR OUT REZZING
GOATMILK:
	.ds		1		;WHAT ELSE A FLAG

CHARMAPS:
	.ds		0
SCORMAP1:
	.ds		16		;CHARACTER MAP FOR PLAYER1 SCORE
SCORMAP2:
	.ds		16		;CHARACTER MAP FOR PLAYER2 SCORE
SCORECMC:
	.ds		16		;CHARACTER MAP FOR COMBO SCORE
SCORCMHS:
	.ds		8		;CHARACTER MAP FOR HIGH SCORE

* RANDOM NUMBER ARRAY (NOT CLEARED EVER)
	org     $2100
RAND:
	.ds		55

* DISPLAY LISTS:
	org     $2200
DISPLIST:
	.ds		0
GAMEDL12:
	.ds		$80		;START OF DISPLAY LISTS, 12 TOTAL
GAMEDL11:
	.ds		$80
GAMEDL10:
	.ds		$80
GAMEDL09:
	.ds		$80
GAMEDL08:
	.ds		$80
GAMEDL07:
	.ds		$80
GAMEDL06:
	.ds		$80
GAMEDL05:
	.ds		$80
GAMEDL04:
	.ds		$80
GAMEDL03:
	.ds		$80
GAMEDL02:
	.ds		$80
GAMEDL01:
	.ds		$80
ENDLIST:
	.ds		$0

YVELH24   EQU     YVELH+24
YVELL24   EQU     YVELL+24
XVELH24   EQU     XVELH+24
XVELL24   EQU     XVELL+24
YPOSH24   EQU     YPOSH+24
YPOSL24   EQU     YPOSL+24
XPOSH24   EQU     XPOSH+24
XPOSL24   EQU     XPOSL+24

